# Numpy

Numpy provides many useful facilities to perform numerical computations including vectors, matrices and linear algebra. It is common to import numpy like this.

In [1]:
import numpy as np

Note that ```np``` acts as an alias or short-hand for ```numpy```.

## 1-d Arrays

Create an array of zeros

In [2]:
x = np.zeros(5)
print(x)

[0. 0. 0. 0. 0.]


These one dimensional arrays are of type ```ndarray```

In [3]:
type(x)

numpy.ndarray

Create an array of ones

In [4]:
x = np.ones(5)
print(x)

[1. 1. 1. 1. 1.]


Add two arrays

In [5]:
x = np.array([1.0, 2.0, 3.0])
y = np.array([4.0, 5.0, 6.0])
z = x + y
print(z)

[5. 7. 9.]


Get the size of array

In [6]:
print(len(x))
print(x.size)

3
3


Get the shape of an array

In [7]:
print(x.shape)

(3,)


## linspace

Generate 10 uniformly spaced numbers in [1,10]

In [8]:
x = np.linspace(1,10,10)
print(x)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


Note that this includes the end points 1 and 10. The output of linspace is an ```ndarray```

In [9]:
type(x)

numpy.ndarray

## Beware of pitfalls - 1

In [10]:
x = np.ones(10)
print(x)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [11]:
x = 0.0
print(x)

0.0


```x``` has changed from an array to a scalar. The correct way is this.

In [12]:
x = np.ones(10)
print(x)
x[:] = 0.0
print(x)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


## Beware of pitfalls - 2

In [13]:
x = np.ones(5)
y = x
x[:] = 0.0
print(x)
print(y)

[0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0.]


Why did ```y``` change ? This happened because ```y``` is just a pointer to ```x```. If we want ```y``` to be an independent copy of ```x``` then do this

In [14]:
x = np.ones(5)
y = x.copy() # y = np.copy(x)
x[:] = 0.0
print(x)
print(y)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]


## 2-d Arrays

2-d arrays can be considered as matrices, though Numpy has a separate matrix class.

Create an array of zeros

In [15]:
A = np.zeros((5,5))
print(A)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Create an array of ones

In [16]:
A = np.ones((2,3))
print(A)

[[1. 1. 1.]
 [1. 1. 1.]]


Create identity matrix

In [17]:
A = np.eye(5)
print(A)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Create an array by specifying its elements

In [18]:
A = np.array([[1.0, 2.0], [3.0, 4.0]])
print(A)

[[1. 2.]
 [3. 4.]]


Create a random array and inspect its shape

In [19]:
m = 2
n = 3
A = np.random.rand(m,n)
print(A)
print(A.shape)
print(A.shape[0])
print(A.shape[1])

[[0.38294691 0.84767744 0.13300111]
 [0.20618881 0.79770041 0.03782909]]
(2, 3)
2
3


Print the elements of an array

In [20]:
for i in range(m):
    for j in range(n):
        print(i,j,A[i,j])

0 0 0.38294690646339113
0 1 0.8476774374591657
0 2 0.1330011103079599
1 0 0.20618880932723727
1 1 0.7977004097650189
1 2 0.0378290947025578


Modify an element

In [21]:
A = np.zeros((3,3))
print(A)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [22]:
A[1,1] = 1.0
print(A)

[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]


## Diagonal matrix creation

In [23]:
a = np.array([1,2,3]) # sub-diagonal
b = np.array([4,5,6,7]) # main diagonal
c = np.array([-1,-2,-3]) # super-diagonal
A = np.diag(a,-1) + np.diag(b,0) + np.diag(c,+1)
print(A)#-1 0 +1对应三条线 看仔细了 这个之前没有接触

[[ 4 -1  0  0]
 [ 1  5 -2  0]
 [ 0  2  6 -3]
 [ 0  0  3  7]]


## Accessing portions of arrays

In [24]:
x = np.linspace(0,9,10)
print(x)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


Get elements ```x[2],...,x[5]```

In [25]:
print(x[2:6])

[2. 3. 4. 5.]


Hence ```x[m:n]``` gives the elements ```x[m],x[m+1],...,x[n-1]```.

Get elements ```x[5]``` upto the last

In [26]:
print(x[5:])

[5. 6. 7. 8. 9.]


Get the last element

In [27]:
print(x[-1])

9.0


Get element ```x[5]``` upto last but one element

In [28]:
print(x[5:-1])

[5. 6. 7. 8.]


Access every alternate element of array

In [29]:
print(x[0::2])

[0. 2. 4. 6. 8.]


In [30]:
print(x[1::2])

[1. 3. 5. 7. 9.]


These operations work on multi dimensional arrays also.

In [31]:
A = np.random.rand(3,4)
print(A)

[[0.38771712 0.02466069 0.88441601 0.00629903]
 [0.65106054 0.52971605 0.67699007 0.49275106]
 [0.82294935 0.93168356 0.50963094 0.5684984 ]]


In [32]:
print(A[0,:]) # 0'th row

[0.38771712 0.02466069 0.88441601 0.00629903]


In [33]:
print(A[:,0]) # 0'th column

[0.38771712 0.65106054 0.82294935]


In [34]:
print(A[0:2,0:3]) # print submatrix

[[0.38771712 0.02466069 0.88441601]
 [0.65106054 0.52971605 0.67699007]]


In [35]:
A[0,:] = 0.0 # zero out zeroth row
print(A)

[[0.         0.         0.         0.        ]
 [0.65106054 0.52971605 0.67699007 0.49275106]
 [0.82294935 0.93168356 0.50963094 0.5684984 ]]


## Arithmetic operations on arrays

Arithmetic operations act element-wise

In [25]:
x = np.array([1.0, 2.0, 3.0])
y = np.array([4.0, 5.0, 6.0])
print(x*y)  # multiply

[ 4. 10. 18.]


In [26]:
print(x/y)  # divide

[0.25 0.4  0.5 ]


In [27]:
print(y**x) # exponentiation

[  4.  25. 216.]


In [28]:
A = np.ones((3,3))
print(A*x) #这里不是矩阵乘 要留心 对应元素相乘

[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


If ```A``` and ```x``` are arrays, then ```A*x``` does not give matrix-vector product. For that use ```dot```

In [40]:
print(A.dot(x))

[6. 6. 6.]


or equivalently

In [41]:
print(np.dot(A,x))

[6. 6. 6.]


In newer Python versions, we can use ```@``` to achieve matrix operations

In [29]:
print(A@x)

[6. 6. 6.]


We can of course do matrix-matrix products using ```dot``` or ```@```

In [30]:
A = np.ones((3,3))
B = 2*A
print('A =\n',A)
print('B =\n',B)
print('A*B =\n',A.dot(B))

A =
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
B =
 [[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]
A*B =
 [[6. 6. 6.]
 [6. 6. 6.]
 [6. 6. 6.]]


## Some array functions

In [44]:
x = np.array([-3,-2,-1,0,1,2,3])
print('min     = ',np.min(x))
print('max     = ',np.max(x))
print('abs min = ',np.abs(x).min())
print('abs max = ',np.abs(x).max())
print('sum     = ',np.sum(x))

min     =  -3
max     =  3
abs min =  0
abs max =  3
sum     =  0


We can compute vector norms using [numpy.linalg.norm](https://numpy.org/doc/stable/reference/generated/numpy.linalg.norm.html) (also see [scipy.linalg.norm](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.norm.html))

In [34]:
from numpy.linalg import norm
print(norm(x))   # L2 norm # norm(x)=(\x1\^2+....\xn\^2)^0.5
print(norm(x,2)) # L2 norm
print(norm(x,1)) # L1 norm

2.0195285781159704
2.0195285781159704
5.681010553814037


## Example: Matrix-vector product

To compute the matrix-vector product $y=Ax$, we can do it element-wise
$$
y_i = \sum_{j=0}^{n-1} A_{ij} x_j, \qquad 0 \le i \le n-1
$$

In [35]:
n = 10
x = np.random.rand(n)
A = np.random.rand(n,n)
y = np.zeros(n)
for i in range(n):
    for j in range(n):
        y[i] += A[i,j]*x[j]
#这个可以直接用

We can verify that our result is correct by this code

In [36]:
print(np.linalg.norm(y-A@x))

6.661338147750939e-16


We can also compute the product column-wise. Let
$$
A_{:,j} = \textrm{j'th column of A}
$$
Then the matrix-vector product can also be written as
$$
y = \sum_{j=0}^{n-1} A_{:,j} x_j
$$

In [37]:
y[:] = 0.0
for j in range(n):
    y += A[:,j]*x[j]

# Now check the result
print(np.linalg.norm(y-A@x))

6.661338147750939e-16


## Example: Matrix-Matrix product

If $A \in R^{m\times n}$ and $B \in R^{n \times p}$ then $C = AB \in R^{m \times p}$ is given by
$$
C_{ij} = \sum_{k=0}^{n-1} A_{ik} B_{kj}
$$

In [38]:
m,n,p = 10,8,6
A = np.random.rand(m,n)
B = np.random.rand(n,p)
C = np.zeros((m,p))
for i in range(m):
    for j in range(p):
        for k in range(n):
            C[i,j] += A[i,k]*B[k,j]

Let us verify the result is correct by computing the Frobenius norm

In [40]:
print(np.linalg.norm(C - A@B)) #掌握这个验证的办法

1.4228624520802642e-15


Another view-point is the following
$$
C_{ij} = (\textrm{i'th row of A}) \cdot (\textrm{j'th column of B})
$$

In [41]:
C[:,:] = 0.0
for i in range(m):
    for j in range(p):
        C[i,j] = A[i,:].dot(B[:,j])

# Now check the result
print(np.linalg.norm(C - A@B))

1.5671457702085671e-15


## Memory ordering in arrays
By default, the ordering is same as in C/C++, the inner-most index is the fastest running one. For example, if we have an array of size (2,3), they are stored in memory in this order
```
a[0,0], a[0,1], a[0,2], a[1,0], a[1,1], a[1,2]
```

In [44]:
a = np.array([[1,2,3], [4,5,6]])
print(a[0,:].data.contiguous, a[:,0].data.contiguous)
a.flags #这个几个新的属性以前没有用过 还不错

True False


  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

To get fortran style ordering, where the outer-most index is the fastest running one, which corresponds to the following layout
```
a[0,0], a[1,0], a[0,1], a[1,1], a[0,2], a[1,2]
```
create like this

In [45]:
b = np.array([[1,2,3], [4,5,6]], order='F')
print(b[0,:].data.contiguous, b[:,0].data.contiguous)
b.flags

False True


  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

## Tensor product array: meshgrid

In [48]:
x = np.linspace(0,3,4)
y = np.linspace(0,2,3)
X, Y = np.meshgrid(x,y)
print('len(x) = ',len(x))
print('len(y) = ',len(y))
print('shape X= ',X.shape)
print('shape Y= ',Y.shape)
print(X)
print(Y)#X和Y是2D网格每个格点的横纵坐标 实际上这里就是一个12个格点的2D网格

len(x) =  4
len(y) =  3
shape X=  (3, 4)
shape Y=  (3, 4)
[[0. 1. 2. 3.]
 [0. 1. 2. 3.]
 [0. 1. 2. 3.]]
[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]]


The output is arranged like this
$$
X[i,j] = x[j], \qquad
Y[i,j] = y[i]
$$
If we want the following arrangement
$$
X[i,j] = x[i], \qquad
Y[i,j] = y[j]
$$
we do the following

In [49]:
Y, X = np.meshgrid(y,x)
print('len(x) = ',len(x))
print('len(y) = ',len(y))
print('shape X= ',X.shape)
print('shape Y= ',Y.shape)

len(x) =  4
len(y) =  3
shape X=  (4, 3)
shape Y=  (4, 3)


## Writing and reading files
Write two 1-D arrays as columns into file

In [51]:
x = np.array([1.0,2.0,3.0,4.0])
y = np.array([2.0,4.0,6.0,8.0])
np.savetxt('data.txt',np.column_stack([x,y]))
#1 2
#2 4
#3 6
#4 8

Check the contents of the file in your terminal
```
cat data.txt
```
We can control the number of decimals saved, and use scientific notation

In [52]:
np.savetxt('data.txt',np.column_stack([x,y]),fmt='%8.4e')

Again check the contents of the file using cat.

We can read the file like this

In [53]:
d = np.loadtxt('data.txt')
x1 = d[:,0]
y1 = d[:,1]
print('x=',x1)
print('y=',y1)

x= [1. 2. 3. 4.]
y= [2. 4. 6. 8.]
